name: Test Incoming Changes
'on':
  pull_request:
    branches: [ main ]
  workflow_dispatch:
permissions: read-all
jobs:
  build-image:
    runs-on: ubuntu-24.04
    env:
      SHELL: /bin/bash
      IMAGE_NAME: quay.io/redhat-best-practices-for-k8s/certsuite-probe:latest

    steps:
      - uses: actions/checkout@v6

      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version: 1.25

      - name: Disable default go problem matcher
        run: echo "::remove-matcher owner=go::"

      - name: Build the image to ensure it builds properly
        run: |
          docker build -t $IMAGE_NAME .
